# Generated by Django 4.2.4 on 2023-08-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coderdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100)),
                ('rating', models.IntegerField(max_length=5)),
                ('rank', models.CharField(max_length=50)),
            ],
        ),
    ]
